on:
  push:
    branches:
      - main

name: main
jobs:
  run_action:
    runs-on: windows-latest

    permissions:
      id-token: write

    steps:
      - name: Install sign cli
        run: dotnet tool install --global sign --version 0.9.1-beta.24325.5

      - name: Copy test library to sign
        shell: cmd
        run: |
          mkdir files
          copy C:\Windows\System32\wmi.dll files

      - name: Azure CLI login with federated credential
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Sign test library
        shell: cmd
        run: |
          sign code trusted-signing --trusted-signing-account ImageMagick --trusted-signing-certificate-profile ImageMagick --trusted-signing-endpoint https://eus.codesigning.azure.net -b %cd%\files *.dll

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wmi
          path: files/wmi.dll
